image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 11 x64
  - yarn

build_script:
  - yarn release

test: off
